name: 'Continuous Integration'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  continuous-integration:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Composer
        uses: php-actions/composer@v6
        with:
          php_version: "8.2"
          php_extensions: pcntl

      - name: Unit Test
        uses: php-actions/phpunit@v3
        with:
          version: "9.5"