name: 'Unit Tests & Static Analysis'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  continuous-integration:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Composer
        uses: php-actions/composer@v6
      - name: Tests
        uses: php-actions/phpunit@v3
        with:
          version: "9.5"
      - name: Static Analysis
        run: "vendor/bin/psalm.phar --long-progress"